/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import javax.swing.JOptionPane;
//import package my_package;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pc
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnuser = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsearchid1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtsearchid2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnsearch3 = new javax.swing.JButton();
        btnsearch1 = new javax.swing.JButton();
        btnsearch2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTable();
        txtsearchid3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEARCH");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(193, 173, 151));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" HOME");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 40, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UPDATE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 50, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SEARCH");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" RECEPTION");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DELETE");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        btnuser.setBackground(new java.awt.Color(0, 0, 0));
        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-user-groups-40.png"))); // NOI18N
        btnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserActionPerformed(evt);
            }
        });
        jPanel2.add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, 60));

        btnsearch.setBackground(new java.awt.Color(0, 0, 0));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-human-research-program-40.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 60, 60));

        btnupdate.setBackground(new java.awt.Color(0, 0, 0));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-update-40.png"))); // NOI18N
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 60, 60));

        btnadd.setBackground(new java.awt.Color(0, 0, 0));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-add-40.png"))); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 60, 60));

        btndel.setBackground(new java.awt.Color(0, 0, 0));
        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-delete-40.png"))); // NOI18N
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        jPanel2.add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 60, 60));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-log-out-48.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 60, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGOUT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/home.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 738, 121));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 507, 241, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-tourist-guide-96 (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 132, 115, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-visitor-100.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 132, 115, 105));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/icons8-street-view-96.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 132, 115, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        jLabel1.setText("REGULAR VISITOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 243, 137, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        jLabel2.setText("GUIDE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 243, 59, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        jLabel3.setText("SENIOR VISITOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 243, 115, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Enter id:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 20));

        txtsearchid1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtsearchid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 90, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Enter id:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, 20));

        txtsearchid2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtsearchid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 90, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Enter id:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        btnsearch3.setBackground(new java.awt.Color(0, 0, 0));
        btnsearch3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch3.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch3.setText("SEARCH");
        btnsearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        btnsearch1.setBackground(new java.awt.Color(0, 0, 0));
        btnsearch1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch1.setText("SEARCH");
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        btnsearch2.setBackground(new java.awt.Color(0, 0, 0));
        btnsearch2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch2.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch2.setText("SEARCH");
        btnsearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 80, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "DOB", "LANGUAGE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(display);
        if (display.getColumnModel().getColumnCount() > 0) {
            display.getColumnModel().getColumn(0).setResizable(false);
            display.getColumnModel().getColumn(1).setResizable(false);
            display.getColumnModel().getColumn(2).setResizable(false);
            display.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 670, 60));

        txtsearchid3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtsearchid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        search s = new search();
     s.setVisible(true);
        this.setVisible(false);
 
        Del a = new Del();
   
    a.show();
    }//GEN-LAST:event_btndelActionPerformed

    private void btnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserActionPerformed
        // TODO add your handling code here:
          search s = new search();
     s.setVisible(true);
        this.setVisible(false);
         user1 u =new user1();
        u.show(true);
        
        
    }//GEN-LAST:event_btnuserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed
        // TODO add your handling code here:
                                                         
    try {
        int guideId = Integer.parseInt(txtsearchid2.getText().trim());
        Guide_Database guideDatabase = new Guide_Database("", 0, "");
        ResultSet rs = guideDatabase.searchGuideById(guideId);

        DefaultTableModel model = (DefaultTableModel) display.getModel();
        model.setRowCount(0); 

        boolean idFound = false;

        while (rs.next()) {
            idFound = true;
            int id = rs.getInt("id");
            String name = rs.getString("name");
            String language = rs.getString("language");
            model.addRow(new Object[]{id, name, language});
        }

        rs.close();

        if (idFound) {
            JOptionPane.showMessageDialog(null, "ID found successfully.");
            txtsearchid2.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "ID not found.");
             txtsearchid2.setText("");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error while searching for guide: " + e.getMessage());
         txtsearchid2.setText("");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid guide ID.");
         txtsearchid2.setText("");
    }


        
    }//GEN-LAST:event_btnsearch1ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
          search s = new search();
     s.setVisible(true);
        this.setVisible(false);
        update u = new update();
        u.show(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                search s = new search();
     s.setVisible(true);
        this.setVisible(false);
 
        Login l = new Login();
   
    l.show();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
          search s = new search();
     s.setVisible(true);
        this.setVisible(false);
        Dashboard1 d =new Dashboard1();
        d.show(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
           search d = new search();
     d.setVisible(true);
        this.setVisible(false);
 
        Add a = new Add();
   
    a.show();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch2ActionPerformed
        // TODO add your handling code here:
                                                         
    String searchIdStr = txtsearchid3.getText().trim();

    if (searchIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a regular visitor ID to search.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int searchId;
    try {
        searchId = Integer.parseInt(searchIdStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid regular visitor ID. Please enter a numeric value.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    RegularVisitor_Database rvDatabase = new RegularVisitor_Database("", 0, "");
    ResultSet rs = rvDatabase.searchVisitorById(searchId);

    if (rs == null) {
        JOptionPane.showMessageDialog(this, "Regular visitor not found or failed to fetch data.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Declare SimpleDateFormat objects
    SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat displayFormat = new SimpleDateFormat("dd-MM-yyyy");

    try {
        if (rs.next()) {
            int id = rs.getInt("ID");
            String name = rs.getString("Name");
            String dobStr = rs.getString("Date of birth");
            
            try {
                // Parse the date from the database format
                Date dob = dbFormat.parse(dobStr);
                
                // Format the date to display format
                String formattedDob = displayFormat.format(dob);
                
                // Display the information in the respective text fields
                txtsearchid3.setText(String.valueOf(id));
           
                // Update the table model with the search result
                DefaultTableModel model = (DefaultTableModel) display.getModel();
                model.setRowCount(0); // Clear existing data
                model.addRow(new Object[]{id, name, formattedDob,"-"});
            } catch (ParseException e) {
                // Handle the parsing exception
                System.err.println("Error parsing date: " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Error parsing date: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Regular visitor not found.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtsearchid3.setText("");
            
            // Clear the table if no data is found
            DefaultTableModel model = (DefaultTableModel) display.getModel();
            model.setRowCount(0);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error while displaying regular visitor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnsearch2ActionPerformed

    private void btnsearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch3ActionPerformed
        // TODO add your handling code here:
                String searchIdStr = txtsearchid1.getText().trim();

    if (searchIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a senior visitor ID to search.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int searchId;
    try {
        searchId = Integer.parseInt(searchIdStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid senior visitor ID. Please enter a numeric value.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    SeniorVisitor_Database svDatabase = new SeniorVisitor_Database("", 0, "");
    ResultSet rs = svDatabase.searchVisitorById(searchId);

    if (rs == null) {
        JOptionPane.showMessageDialog(this, "senior visitor not found or failed to fetch data.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Declare SimpleDateFormat objects
    SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat displayFormat = new SimpleDateFormat("dd-MM-yyyy");

    try {
        if (rs.next()) {
            int id = rs.getInt("ID");
            String name = rs.getString("Name");
            String dobStr = rs.getString("Date of birth");
            
            try {
                // Parse the date from the database format
                Date dob = dbFormat.parse(dobStr);
                
                // Format the date to display format
                String formattedDob = displayFormat.format(dob);
                
                // Display the information in the respective text fields
                txtsearchid1.setText(String.valueOf(id));
              
                // Update the table model with the search result
                DefaultTableModel model = (DefaultTableModel) display.getModel();
                model.setRowCount(0); // Clear existing data
                model.addRow(new Object[]{id, name, formattedDob,"-"});
            } catch (ParseException e) {
                // Handle the parsing exception
                System.err.println("Error parsing date: " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Error parsing date: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "senior visitor not found.", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtsearchid1.setText("");
          
            // Clear the table if no data is found
            DefaultTableModel model = (DefaultTableModel) display.getModel();
            model.setRowCount(0);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error while displaying senior visitor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnsearch3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsearch1;
    private javax.swing.JButton btnsearch2;
    private javax.swing.JButton btnsearch3;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnuser;
    private javax.swing.JTable display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtsearchid1;
    private javax.swing.JTextField txtsearchid2;
    private javax.swing.JTextField txtsearchid3;
    // End of variables declaration//GEN-END:variables
}
